services:
  postgres:
    container_name: starcine-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: starcine
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
